/**
 * Pure Content-Security-Policy builder with per-request nonce.
 *
 * Exports:
 * - generateNonce(): generates a fresh 128-bit CSPRNG nonce (base64, padding stripped)
 * - buildContentSecurityPolicy(nonce: string, isDev?: boolean): builds the full CSP header value
 * - CSP_NONCE_HEADER: shared header name constant "x-nonce"
 * - CSP_HEADER: shared header name constant "Content-Security-Policy"
 */

import type {} from "next/server";

export const CSP_NONCE_HEADER = "x-nonce";
export const CSP_HEADER = "Content-Security-Policy";

/**
 * Generates a fresh 128-bit CSPRNG nonce, base64-encoded with padding stripped.
 * 16 bytes → 22 base64 characters (after removing trailing `=`).
 */
export function generateNonce(): string {
  const array = new Uint8Array(16);
  crypto.getRandomValues(array);
  return btoa(String.fromCharCode(...array)).replace(/=+$/, "");
}

/**
 * Builds the full Content-Security-Policy header value using the given nonce.
 *
 * - `script-src` includes the nonce and `'strict-dynamic'` (prod) or `unsafe-eval` (dev)
 * - All other directives are shared across environments
 *
 * @param nonce - The per-request nonce generated by generateNonce()
 * @param isDev - Whether running in development mode (defaults to process.env.NODE_ENV !== "production")
 */
export function buildContentSecurityPolicy(
  nonce: string,
  isDev?: boolean,
): string {
  const dev = isDev ?? process.env.NODE_ENV !== "production";

  const scriptSrc = [
    "'self'",
    `'nonce-${nonce}'`,
    "strict-dynamic",
    "https://challenges.cloudflare.com",
    dev ? "'unsafe-eval'" : "",
  ]
    .filter((s) => s)
    .join(" ");

  const connectSrc = [
    "'self'",
    "https://*.supabase.co",
    "https://challenges.cloudflare.com",
    dev ? "ws:" : "",
  ]
    .filter((s) => s)
    .join(" ");

  return [
    "default-src 'self'",
    `script-src ${scriptSrc}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' blob: data: https://*.supabase.co",
    "font-src 'self' data:",
    `connect-src ${connectSrc}`,
    "frame-src https://challenges.cloudflare.com",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "upgrade-insecure-requests",
  ].join("; ");
}